export type RunnerSurface = 'unit' | 'golden' | 'mcp';

export interface RunnerSelectionRegistry {
  readonly groups: ReadonlySet<string>;
  readonly cases: ReadonlySet<string>;
}

/**
 * Exact owner-file registration for platform contract surface/group/case tuples.
 * Paths are repository-relative POSIX paths.
 */
export const PLATFORM_CASE_OWNER_REGISTRATION: Readonly<
  Record<string, readonly string[]>
> = Object.freeze({
  'unit/cross-platform-baseline/repository-path-invalid-input': Object.freeze([
    'test/unit/cross-platform-platform.spec.ts',
  ]),
  'unit/cross-platform-baseline/repository-path-posix-symlink-escape':
    Object.freeze(['test/unit/cross-platform-platform.spec.ts']),
  'unit/cross-platform-baseline/repository-path-windows-reparse-escape':
    Object.freeze(['test/unit/cross-platform-platform.spec.ts']),
  'unit/cross-platform-baseline/repository-path-error-redaction': Object.freeze([
    'test/unit/cross-platform-platform.spec.ts',
  ]),
  'unit/cross-platform-baseline/process-caller-abort-tree-cleanup':
    Object.freeze(['test/unit/cross-platform-platform.spec.ts']),
  'unit/cross-platform-baseline/process-timeout-tree-cleanup': Object.freeze([
    'test/unit/cross-platform-platform.spec.ts',
  ]),
  'unit/cross-platform-baseline/process-stdout-n-plus-one-boundary':
    Object.freeze(['test/unit/cross-platform-platform.spec.ts']),
  'unit/cross-platform-baseline/process-stderr-n-plus-one-boundary':
    Object.freeze(['test/unit/cross-platform-platform.spec.ts']),
  'unit/cross-platform-baseline/process-cleanup-invariant-fault': Object.freeze([
    'test/unit/cross-platform-platform.spec.ts',
  ]),
  'mcp/mcp-surface/request-cancellation-cleanup': Object.freeze([
    'test/mcp/request-cancellation.spec.ts',
  ]),
  'mcp/lifecycle/shutdown-cleanup-probe': Object.freeze([
    'test/mcp/lifecycle-contract.spec.ts',
  ]),
  'unit/cross-platform-ci-contract/workflow-matrix-contract': Object.freeze([
    'test/unit/cross-platform-ci-contract.spec.ts',
  ]),
  'unit/cross-platform-ci-contract/runtime-cell-contract': Object.freeze([
    'test/unit/cross-platform-ci-contract.spec.ts',
  ]),
  'unit/cross-platform-ci-contract/safe-platform-report': Object.freeze([
    'test/unit/platform-evidence-report.spec.ts',
  ]),
  'unit/cross-platform-ci-contract/synthetic-extension-protocol': Object.freeze([
    'test/unit/cross-platform-ci-contract.spec.ts',
  ]),
  'unit/streaming-ripgrep/process-n-plus-one-boundary': Object.freeze([
    'test/unit/safe-process-streaming-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/process-terminal-races': Object.freeze([
    'test/unit/safe-process-streaming-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/consumer-progress-contract': Object.freeze([
    'test/unit/safe-process-streaming-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/buffered-compatibility-projection': Object.freeze([
    'test/unit/safe-process-streaming-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/stream-consumer-finalizer-and-process-exit':
    Object.freeze(['test/unit/safe-process-streaming-v2.spec.ts']),
  'unit/streaming-ripgrep/stream-consumer-progress-and-boundary': Object.freeze([
    'test/unit/safe-process-streaming-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/json-line-partitions': Object.freeze([
    'test/unit/ripgrep-json-line-consumer-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/json-line-invalid': Object.freeze([
    'test/unit/ripgrep-json-line-consumer-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/protocol-fsm-and-offsets': Object.freeze([
    'test/unit/ripgrep-json-line-consumer-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/ripgrep-json-stream-protocol': Object.freeze([
    'test/unit/ripgrep-json-line-consumer-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/max-hits-groups': Object.freeze([
    'test/unit/ripgrep-streaming-backend-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/multi-view-cap-and-order': Object.freeze([
    'test/unit/ripgrep-streaming-backend-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/exit-outcome-table': Object.freeze([
    'test/unit/ripgrep-streaming-backend-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/outcome-schema': Object.freeze([
    'test/unit/backend-execution-outcome-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/codegraph-outcome-trace': Object.freeze([
    'test/unit/backend-execution-trace-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/physical-start-authority': Object.freeze([
    'test/unit/backend-physical-attempt-executor-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/eligibility-gate': Object.freeze([
    'test/unit/canonical-locate-execution.spec.ts',
  ]),
  'unit/streaming-ripgrep/v1-parity-and-trace': Object.freeze([
    'test/unit/canonical-locate-execution.spec.ts',
  ]),
  'unit/streaming-ripgrep/backend-trace-closure': Object.freeze([
    'test/unit/backend-execution-trace-v2.spec.ts',
  ]),
  'unit/streaming-ripgrep/real-cleanup': Object.freeze([
    'test/unit/process-cleanup.spec.ts',
  ]),
  'unit/streaming-ripgrep/ripgrep-early-stop-tree-cleanup': Object.freeze([
    'test/unit/process-cleanup.spec.ts',
  ]),
  'golden/streaming-ripgrep/large-streaming-ripgrep': Object.freeze([
    'test/golden/large-streaming-ripgrep.spec.ts',
  ]),
  'unit/input-abort-contract-v2/repository-path-input': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/file-anchor-input': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/semantic-input': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/question-non-interference': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/raw-budget': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/platform-input-boundary': Object.freeze([
    'test/unit/locate-request-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/cli-input-contract': Object.freeze([
    'test/unit/cli-input-contract-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/abort-first-writer': Object.freeze([
    'test/unit/locate-abort-coordinator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/platform-abort-first-writer': Object.freeze([
    'test/unit/locate-abort-coordinator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/finalization-latch': Object.freeze([
    'test/unit/canonical-locate-finalization-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/platform-finalization-latch': Object.freeze([
    'test/unit/canonical-locate-finalization-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/backend-attempt-aggregation': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/index-observation-matrix': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/strategy-completeness': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/contribution-trust': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/public-materialization-order': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/status-priority': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/next-action-policy': Object.freeze([
    'test/unit/request-outcome-aggregator-v2.spec.ts',
  ]),
  'unit/input-abort-contract-v2/aggregator-owner-direct-integration':
    Object.freeze(['test/unit/request-outcome-aggregator-v2.spec.ts']),
  'unit/input-abort-contract-v2/outcome-proof': Object.freeze([
    'test/unit/canonical-locate-facts-bridge.spec.ts',
  ]),
  'unit/input-abort-contract-v2/v1-compatibility': Object.freeze([
    'test/unit/canonical-locate-execution.spec.ts',
  ]),
  'golden/input-abort-contract-v2/v1-compatibility': Object.freeze([
    'test/golden/input-abort-contract-v2.spec.ts',
  ]),
  'golden/input-abort-contract-v2/large-request-outcome-permutation':
    Object.freeze(['test/golden/large-synthetic-repository.spec.ts']),
  'mcp/input-abort-contract-v2/mcp-input-and-cancel': Object.freeze([
    'test/mcp/request-cancellation-v2.spec.ts',
  ]),
});

export const RUNNER_GROUP_ALIASES: Readonly<
  Record<RunnerSurface, Readonly<Record<string, readonly string[]>>>
> = Object.freeze({
  unit: Object.freeze({}),
  golden: Object.freeze({
    classification: Object.freeze([
      'classification',
      'text-engine-classifier',
      'text-evidence-engine',
    ]),
    candidate: Object.freeze(['candidate', 'candidate-policy']),
    'backend-transitions': Object.freeze([
      'backend-transitions',
      'codegraph-fallback',
      'text-evidence-engine',
    ]),
    security: Object.freeze(['security', 'output-redaction']),
    'final-status': Object.freeze(['final-status', 'result-limits']),
  }),
  mcp: Object.freeze({
    protocol: Object.freeze(['mcp-surface']),
    lifecycle: Object.freeze(['lifecycle']),
  }),
});

export const RUNNER_SELECTIONS: Readonly<
  Record<RunnerSurface, RunnerSelectionRegistry>
> = Object.freeze({
  unit: Object.freeze({
    groups: new Set([
      'runner-smoke',
      'contract',
      'di',
      'repository-safety',
      'reader-limits',
      'reader-failures',
      'process-contract',
      'process-output-isolation',
      'process-cleanup',
      'ripgrep-backend',
      'evidence-merge',
      'direct-mapping-classifier',
      'evidence-id-order',
      'candidate-truth-table',
      'candidate-discovery',
      'candidate-context',
      'candidate-classification',
      'candidate-budget',
      'candidate-permutation',
      'codegraph-probe',
      'codegraph-parser',
      'codegraph-query-plan',
      'codegraph-live-smoke',
      'locate-status',
      'output-guardrails',
      'debug-cli-shell',
      'debug-cli-lifecycle',
      'debug-cli-locate',
      'debug-cli-probe',
      'debug-cli-golden',
      'public-output-v2',
      'canonical-locate-bridge',
      'request-snapshot-cache',
      'relevance-ranking-budget',
      'cross-platform-ci-contract',
      'cross-platform-baseline',
      'streaming-ripgrep',
      'input-abort-contract-v2',
    ]),
    cases: new Set([
      'runner-smoke',
      'term-case-parity',
      'scope-gate-runtime',
      'di-assembly',
      'canonical-fact-contract',
      'canonical-required-owner-finalizer',
      'canonical-materialization-seam',
      'canonical-single-execution',
      'canonical-v1-projector-parity',
      'canonical-v1-shadow-isolation',
      'canonical-term-case-parity',
      'canonical-real-shadow-no-cutover',
      'canonical-synthetic-shadow-serialization',
      'canonical-safe-error-serialization',
      'canonical-di-wiring',
      'canonical-transport-reachability',
      'canonical-package-declaration-boundary',
      'windows-reparse-policy',
      'reader-limits',
      'reader-failures',
      'process-contract',
      'process-output-isolation',
      'reader-abort-no-late-completion',
      'ripgrep-backend',
      'evidence-merge',
      'direct-mapping-classifier',
      'evidence-id-order',
      'secondary-backend-provenance-table',
      'candidate-discovery',
      'candidate-context',
      'discovery-key-mutual-exclusion',
      'candidate-budget',
      'candidate-permutation',
      'codegraph-probe',
      'codegraph-parser',
      'codegraph-query-plan',
      'indexed-temp-repo',
      'transition-matrix-completeness',
      'hit-unverified-fallback-complete',
      'hit-unverified-fallback-unavailable',
      'caller-abort-empty',
      'caller-abort-with-evidence',
      'internal-deadline-below-max',
      'internal-deadline-at-max',
      'redaction-policy',
      'debug-cli-shell',
      'debug-cli-lifecycle',
      'debug-cli-locate',
      'debug-cli-probe',
      'debug-cli-golden',
      'schema-contract-families',
      'field-redaction',
      'location-redaction',
      'span-redaction',
      'corpus-policy',
      'corpus-boundaries',
      'phone-corpus-policy',
      'redaction-amplification',
      'public-safe-ranking-key',
      'assembler-allowlist',
      'ordinal-ids',
      'derived-status',
      'safe-errors',
      'synthetic-parity',
      'no-cutover-import-inventory',
      'resource-budget-primitives',
      'raw-resource-budgets',
      'corpus-resource-budgets',
      'public-field-resource-budgets',
      'serialized-resource-budget',
      'maximum-structure-budget',
      'resource-budget-ordering',
      'resource-budget-projection',
      'resource-budget-legacy-isolation',
      'workflow-matrix-contract',
      'runtime-cell-contract',
      'safe-platform-report',
      'synthetic-extension-protocol',
      'repository-path-invalid-input',
      'repository-path-posix-symlink-escape',
      'repository-path-windows-reparse-escape',
      'repository-path-error-redaction',
      'process-caller-abort-tree-cleanup',
      'process-timeout-tree-cleanup',
      'process-stdout-n-plus-one-boundary',
      'process-stderr-n-plus-one-boundary',
      'process-cleanup-invariant-fault',
      'anchor-intent-normalization',
      'discovery-anchor-file-reservation',
      'match-priority-truth-table',
      'real-classifier-ranking',
      'public-safe-ranking-order',
      'anchor-satisfaction-truth-table',
      'anchor-record-reservation',
      'cross-file-round-robin',
      'unsatisfied-anchor-ledger',
      'ranking-permutation',
      'ranking-trust-finalizer',
      'public-materialization-source-stage',
      'public-materialization-real-adapter',
      'ranking-real-envelope',
      'v1-no-cutover',
      'request-file-cache-single-decode',
      'request-file-cache-canonical-alias',
      'discovery-reservation-budget-independence',
      'scope-pre-cap-fold',
      'legacy-scope-policy-pool',
      'verified-record-cache-preverification-reuse',
      'pre-ranking-stable-pool',
      'snapshot-v1-parity',
      'snapshot-coverage-truth-table',
      'snapshot-outcome-contribution',
      'snapshot-mutation-purge',
      'snapshot-failure-and-abort-purge',
      'snapshot-v1-mutation-precedence',
      'snapshot-trust-finalizer',
      'producer-basis-receipts',
      'verified-language-consumer-carrier',
      'scope-coverage-basis',
      'snapshot-git-state',
      'snapshot-real-envelope',
      'executor-dual-lane-wiring',
      'process-n-plus-one-boundary',
      'process-terminal-races',
      'consumer-progress-contract',
      'buffered-compatibility-projection',
      'stream-consumer-finalizer-and-process-exit',
      'stream-consumer-progress-and-boundary',
      'json-line-partitions',
      'json-line-invalid',
      'protocol-fsm-and-offsets',
      'ripgrep-json-stream-protocol',
      'max-hits-groups',
      'multi-view-cap-and-order',
      'exit-outcome-table',
      'outcome-schema',
      'codegraph-outcome-trace',
      'physical-start-authority',
      'eligibility-gate',
      'v1-parity-and-trace',
      'backend-trace-closure',
      'real-cleanup',
      'ripgrep-early-stop-tree-cleanup',
      'repository-path-input',
      'file-anchor-input',
      'semantic-input',
      'question-non-interference',
      'raw-budget',
      'platform-input-boundary',
      'cli-input-contract',
      'abort-first-writer',
      'platform-abort-first-writer',
      'finalization-latch',
      'platform-finalization-latch',
      'backend-attempt-aggregation',
      'index-observation-matrix',
      'strategy-completeness',
      'contribution-trust',
      'public-materialization-order',
      'status-priority',
      'next-action-policy',
      'aggregator-owner-direct-integration',
      'outcome-proof',
      'v1-compatibility',
      'mcp-input-and-cancel',
    ]),
  }),
  golden: Object.freeze({
    groups: new Set([
      'runner-smoke',
      'text-engine-classifier',
      'text-evidence-engine',
      'candidate-policy',
      'codegraph-fallback',
      'result-limits',
      'output-redaction',
      'classification',
      'candidate',
      'backend-transitions',
      'security',
      'final-status',
      'verification-contract',
      'performance',
      'public-output-v2',
      'canonical-locate-bridge',
      'request-snapshot-cache',
      'relevance-ranking-budget',
      'streaming-ripgrep',
      'input-abort-contract-v2',
    ]),
    cases: new Set([
      'runner-smoke',
      'canonical-v1-bridge-parity',
      'snapshot-mutation-golden',
      'z-target-small-budget',
      'multi-anchor-round-robin',
      'large-ranking-permutation',
      'large-repository-request-cache',
      'large-streaming-ripgrep',
      'large-request-outcome-permutation',
      'v1-compatibility',
      'manifest-schema',
      'evaluator-smoke',
      'source-field-mapping',
      'false-confirmation-decoys',
      'exclusion-summary',
      'text-engine-baseline',
      'ripgrep-unavailable',
      'ripgrep-failed',
      'ripgrep-incomplete',
      'ripgrep-timeout',
      'sibling-candidate',
      'alias-candidate',
      'sibling-false-positive',
      'codegraph-missing',
      'codegraph-no-result',
      'codegraph-failed',
      'codegraph-incomplete',
      'codegraph-global-abort-no-fallback',
      'codegraph-local-timeout-fallback',
      'codegraph-hit-unverified',
      'codegraph-symbol-complete-no-fallback',
      'codegraph-secondary-provenance-table',
      'backend-unavailable',
      'partial-empty-limit',
      'partial-with-evidence',
      'secret-redaction',
      'redaction-metadata',
      'manifest-evaluator',
      'evaluator-negative-self-test',
      'fixture-completeness',
      'large-synthetic-repository',
      'classification-syntax-family',
      'candidate-family-contract',
      'backend-transition-family',
      'security-family-contract',
      'final-status-family-contract',
      'contract-code-probes',
      'public-output-v2-projection',
      'public-output-v2-determinism',
      'redaction-amplification',
    ]),
  }),
  mcp: Object.freeze({
    groups: new Set([
      'runner-smoke',
      'mcp-surface',
      'protocol',
      'lifecycle',
      'input-abort-contract-v2',
    ]),
    cases: new Set([
      'runner-smoke',
      'lifecycle-manifest-schema',
      'mcp-input-and-cancel',
      'initialize-tools-capability',
      'tool-list-schema',
      'single-tool-readonly',
      'unknown-tool-jsonrpc-boundary',
      'source-field-mapping',
      'recoverable-status-parity',
      'invalid-input',
      'invalid-repo',
      'path-outside-root',
      'internal-error-parity',
      'request-cancellation-cleanup',
      'stdio-clean-output',
      'stdio-graceful-shutdown',
      'shutdown-cleanup-probe',
      'candidate-minimal-loop',
      'redaction-output-parity',
      'mcp-golden-adapter',
    ]),
  }),
});
